name: test_app_mrz
description: "FREE MRZ Scanner - Direct MRZ detection using Google ML Kit"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # FREE Google ML Kit for text recognition
  google_mlkit_text_recognition: ^0.15.0
  
  # Camera and image handling  
  camera: ^0.11.0+2
  image: ^4.1.3
  
  # FREE MRZ parsing library
  mrz_parser: ^2.0.0
  
  # Permissions
  permission_handler: ^11.3.0
  
  cupertino_icons: ^1.0.8
  flutter_tesseract_ocr: ^0.4.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
