name: hotel_staff_app
description: ITSthe1 Hotel Guest Management System - Mobile-First ID/Passport Scanning App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  
  # Camera & Image Processing
  camera: ^0.11.2
  image_picker: ^1.1.3
  image: ^4.3.0
  image_cropper: ^8.0.2
  
  # OCR & Document Scanning (FREE LIBRARIES ONLY)
  google_mlkit_text_recognition: ^0.15.0  # FREE Google ML Kit
  mrz_parser: ^2.0.0                       # FREE MRZ parser
  flutter_tesseract_ocr: ^0.4.30           # FREE Tesseract OCR (updated)
  
  # State Management & Navigation
  provider: ^6.1.2
  go_router: ^14.6.2
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: false  # Disabled - iOS project not configured
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FF8C42"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  min_sdk_android: 21
